from typing import List, TypedDict, Dict, Any
from pydantic import BaseModel, Field
from langchain_core.documents import Document

class AgentState(TypedDict):
    """
    Represents the complete state engine of our self-correcting RAG graph.
    """
    question: str                # The original user query
    transformed_query: str       # The optimized query generated for web-search
    generation: str             # The current response generated by the LLM
    documents: List[Document]    # The list of active working documents (retrieved or searched)
    search_needed: bool          # Flag determining if web fallback fallback loop should trigger
    hallucination_retry: int     # Counter to prevent infinite loops if LLM keeps hallucinating
    steps: List[str]             # Trace log tracking which nodes executed (Auditing layer)

# --- Structured Output Schemas ---
# These Pydantic classes will enforce the open-source LLM to return strict JSON
# structures when acting as an evaluator/grader node instead of raw strings.

class GradeDocuments(BaseModel):
    """Binary score for relevance check on a retrieved document."""
    binary_score: str = Field(
        description="Document is relevant to the question, 'yes' or 'no'"
    )

class GradeHallucination(BaseModel):
    """Binary score for hallucination quiz on generation."""
    binary_score: str = Field(
        description="Generation is grounded in / supported by the documents, 'yes' or 'no'"
    )

class GradeAnswer(BaseModel):
    """Binary score to evaluate if response addresses the user question."""
    binary_score: str = Field(
        description="Generation addresses the user question completely, 'yes' or 'no'"
    )